### ISSUE TITLE
Focal lxd serie fail

### ISSUE THREAD

**Issue by redno2** [canonical/charm-lxd#52]
lxd failed to be deployed when it is using in deployed focal machine. 

The test.

$ juju deploy ...yaml
```
description: Test
series: focal
services:
  easyrsa:
    charm: cs:~containers/easyrsa-441
    constraints: root-disk=8G
    num_units: 1
    resources:
      easyrsa: 5
    to:
    - lxd:etcd
  etcd:
    charm: cs:~containers/etcd-655
    constraints: tags=virtual,k8s,bvt zones=k8s-bvt
    num_units: 1
```

The result:
```

Model    Controller  Cloud/Region  Version  SLA          Timestamp
k8s-bvt  maas        maas          2.9.22   unsupported  17:44:59+01:00

App      Version  Status   Scale  Charm    Store       Rev  OS      Notes
easyrsa           waiting    0/1  easyrsa  jujucharms  441  ubuntu  
etcd     3.4.5    blocked      1  etcd     jujucharms  655  ubuntu  

Unit       Workload  Agent       Machine   Public address  Ports  Message
easyrsa/8  waiting   allocating  24/lxd/0                         waiting for machine
etcd/8*    blocked   idle        24        10.168.168.57          Missing relation to certificate authority.

Machine   State    DNS            Inst id           Series  AZ       Message
24        started  10.168.168.57  host  focal   k8s-bvt  Deployed
24/lxd/0  pending                 pending           focal   

```
Errors :
```
machine-192: 16:48:37 WARNING juju.container-setup not stopping machine agent container watcher due to error: setting up container dependencies on host machine: Get "http://unix.socket/1.0": dial unix /var/snap/lxd/common/lxd/unix.socket: connect: connection refused
machine-192: 16:48:37 ERROR juju.container-setup starting container provisioner for lxd: setting up container dependencies on host machine: Get "http://unix.socket/1.0": dial unix /var/snap/lxd/common/lxd/unix.socket: connect: connection refused
```

Seem to have an old version of lxd, fixed in the charm ?
```
$ juju model-config lxd-snap-channel
4.17/stable

$ juju ssh 24
ubuntu@host:~$ snap list
Name    Version    Rev    Tracking       Publisher   Notes
lxd     4.17       21390  4.17/stable    canonical✓  -

```
This fix the issue
```
$ juju model-config lxd-snap-channel=4.23/stable
....
```

Thanks
